### PR TITLE
sycl build request from Google

### PR DESCRIPTION
**Pull request by guizili0**
below is the usage:

workspace=$1
xla_path=$workspace/xla
cd $workspace
git clone -b guizili/build https://github.com/Intel-tensorflow/xla xla
**bash $xla_path/tools/ci_build/sycl_build/build_sycl.sh $workspace**

### CODE REVIEW

**Comment by Zantares** [comment]
Missing the remove step, the script should be:
```shell
workspace=$1
SCRIPT_PATH="dirname \"$0\""
xla_path=$workspace/xla
cd $workspace
git clone -b guizili/build https://github.com/Intel-tensorflow/xla xla
bash $SCRIPT_PATH/install_bazel.sh $workspace
bash $xla_path/build_tools/sycl/install_oneapi.sh $workspace install
#bash $SCRIPT_PATH/install_l0.sh $workspace
cd $workspace
bash $xla_path/build_tools/sycl/build_xla.sh $workspace
bash $xla_path/build_tools/sycl/clean.sh $workspace
```

**Comment by Zantares** [comment]
> Missing the remove step, the script should be:
> 
> ```shell
> workspace=$1
> SCRIPT_PATH="dirname \"$0\""
> xla_path=$workspace/xla
> cd $workspace
> git clone -b guizili/build https://github.com/Intel-tensorflow/xla xla
> bash $SCRIPT_PATH/install_bazel.sh $workspace
> bash $xla_path/build_tools/sycl/install_oneapi.sh $workspace install
> #bash $SCRIPT_PATH/install_l0.sh $workspace
> cd $workspace
> bash $xla_path/build_tools/sycl/build_xla.sh $workspace
> bash $xla_path/build_tools/sycl/clean.sh $workspace
> ```

@guizili0 should we make these cmd as a new script for ci test like https://github.com/Intel-tensorflow/xla/tree/main/tools/ci_build/gpu_build?

**Comment by guizili0** [comment]
> > Missing the remove step, the script should be:
> > ```shell
> > workspace=$1
> > SCRIPT_PATH="dirname \"$0\""
> > xla_path=$workspace/xla
> > cd $workspace
> > git clone -b guizili/build https://github.com/Intel-tensorflow/xla xla
> > bash $SCRIPT_PATH/install_bazel.sh $workspace
> > bash $xla_path/build_tools/sycl/install_oneapi.sh $workspace install
> > #bash $SCRIPT_PATH/install_l0.sh $workspace
> > cd $workspace
> > bash $xla_path/build_tools/sycl/build_xla.sh $workspace
> > bash $xla_path/build_tools/sycl/clean.sh $workspace
> > ```
> 
> @guizili0 should we make these cmd as a new script for ci test like https://github.com/Intel-tensorflow/xla/tree/main/tools/ci_build/gpu_build?

Updated @Zantares 
the new BKM to build is:
workspace=$1
SCRIPT_PATH="`dirname \"$0\"`"
xla_path=$workspace/xla
cd $workspace
git clone -b guizili/build https://github.com/Intel-tensorflow/xla xla
bash $xla_path/tools/ci_build/sycl_build/build_sycl.sh $workspace

**Review by Zantares — APPROVED** [review]

**Comment by Zantares** [comment]
LGTM, I think we can submit this PR to stock OpenXLA now.

**Comment by guizili0** [comment]
> LGTM, I think we can submit this PR to stock OpenXLA now.

@ShengYang1 can you help on this? thanks.

**Comment by ShengYang1** [comment]
https://github.com/openxla/xla/pull/11767

**Comment by Zantares** [comment]
Public PR is submitted: https://github.com/openxla/xla/pull/11767, close this one.

**Pull request closed without merging**
